import { User } from "@/types/auth";

export const mockUsers: User[] = [
  {
    id: "CIT-001",
    name: "Arun Kumar",
    email: "citizen1@example.com",
    password: "Password123",
    role: "citizen",
    constituency: "North Chennai",
    state: "Tamil Nadu",
    district: "Chennai",
    profilePhoto: "",
  },
  {
    id: "CIT-002",
    name: "Priya Sharma",
    email: "citizen2@example.com",
    password: "Password123",
    role: "citizen",
    constituency: "South Mumbai",
    state: "Maharashtra",
    district: "Mumbai",
    profilePhoto: "",
  },
  {
    id: "CIT-003",
    name: "Rahul Patel",
    email: "citizen3@example.com",
    password: "Password123",
    role: "citizen",
    constituency: "Central Surat",
    state: "Gujarat",
    district: "Surat",
    profilePhoto: "",
  },
  {
    id: "MP-001",
    name: "Dr. Rajesh Sharma",
    email: "mp.northchennai@gov.in",
    password: "Password123",
    role: "mp",
    constituency: "North Chennai",
    state: "Tamil Nadu",
    district: "Chennai",
    profilePhoto: "",
  },
  {
    id: "MP-002",
    name: "Smt. Meera Desai",
    email: "mp.mumbai@gov.in",
    password: "Password123",
    role: "mp",
    constituency: "South Mumbai",
    state: "Maharashtra",
    district: "Mumbai",
    profilePhoto: "",
  },
  {
    id: "MP-003",
    name: "Shri Amit Joshi",
    email: "mp.surat@gov.in",
    password: "Password123",
    role: "mp",
    constituency: "Central Surat",
    state: "Gujarat",
    district: "Surat",
    profilePhoto: "",
  },
];
